### ISSUE TITLE
"Try It Out" gives response "TypeError: r is undefined" only on UI

### ISSUE THREAD

**Issue by rsveltman** [robzsk/swagger-ui-alone#1]
Hi, I'm using swagger-ui-alone to serve a documentation page for my API. Here's my controller, docs.js:

```
var yaml = require("js-yaml");
var fs = require('fs');
var spec = yaml.load(fs.readFileSync("api/swagger/swagger.yaml"));

const alone = require('swagger-ui-alone');

// turn your spec into a swagger-ui page
const docs = alone(spec);

module.exports = {
  getDocs: getDocs
};

function getDocs(req, res){
    fs.writeFileSync('documentation/index.html', docs);
    res.sendFile(process.cwd() + '/documentation/index.html');
}
```
And this makes the documentation show up alright. The only problem is when I try any of the "Try It Out" buttons to test the API through the Swagger UI, it always shows a Server Response with no apparent code, and under Details it says "TypeError: r is undefined". 

This doesn't happen when I use curl to send the exact same requests. I've also concluded that this is a problem with the UI because while investigating the code, I discovered that there is a variable called "r" being used by the UI.
When I inspected the "Execute" button on the browser inspector, I saw that there was a click event tied to it, and the click event led to this:

```
function() {
  var e = r.props,
    t = e.specSelectors,
    n = e.specActions,
    i = e.operation,
    o = e.path,
    a = e.method;
  n.validateParams([o, a]), t.validateBeforeExecute([o, a]) && (r.props.onExecute && r.props.onExecute(), n.execute({
    operation: i,
    path: o,
    method: a
  }))
}
```

I believe the `r` being used in this function is the "r" that is `undefined`. Does this look familiar to you? What's causing `r` to be undefined?

**Comment by robzsk** [comment]
Interesting.

```
const alone = require('swagger-ui-alone');
const express = require('express');

// example spec, insert your own here
const spec = {
  swagger: '2.0',
  info: { version: '0.0.1', title: 'Spec Title' },
  paths: { '/foo': { get: { responses: { '200': { description: 'OK' } } } } },
};

// turn your spec into a swagger-ui page
const docs = alone(spec);

const app = express();

app.get('/', (req, res) => res.send(docs));
app.get('/foo', (req, res) => {
  res.send({
    foo: 'bar',
  })
});

app.listen(8080, () => console.log('server started.'));
```
I've implemented the `/foo` endpoint above using express and it's working as expected, tested in Firefox 59.0.2, Chrome 65 and Safari 10.
```
Response body:
{
  "foo": "bar"
}
```

Which browser are you using?

**Comment by rsveltman** [comment]
@robzsk I'm using Firefox Quantum. I hadn't thought of trying with different browsers, I'll test it with Chrome as well.

**Comment by rsveltman** [comment]
I'm still not sure what "r" had to do with any of it, but the problem went away when I removed `- http` from `schemes: ` in `swagger.yaml`. It was sending the request as http even though both http and https were options, but now it sends it as https, and it works as expected. Testing it on Chrome gave me a slightly different error at first, which did help me figure out what to do.
